export const START_FETCH_LOOP = 'START_FETCH_LOOP';
export const STOP_FETCH_LOOP = 'STOP_FETCH_LOOP';

export const IDENTITY_VERIFY_SUCCESS = 'IDENTITY_VERIFY_SUCCESS';
export const START_EMAIL = 'START_EMAIL';
export const START_CONFIRMATION = 'START_CONFIRMATION';
export const START_JOIN_CHANNEL = 'START_JOIN_CHANNEL';
export const JOIN_CHANNEL = 'JOIN_CHANNEL';

export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_APPEND_SUCCESS = 'FETCH_MESSAGES_APPEND_SUCCESS';
export const FETCH_MESSAGES_ERROR = 'FETCH_MESSAGES_ERROR';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';

export const FETCH_CHANNEL_MEMBERS_SUCCESS = 'FETCH_CHANNEL_MEMBERS_SUCCESS';
export const FETCH_MEMBERS_CARDS_SUCCESS = 'FETCH_MEMBERS_CARDS_SUCCESS';
