module.exports = {
	'10000': 'Internal application error',
	'20100': 'The request ID header was used already',
	'20101': 'The request ID header is invalid',
	'20200': 'The request sing header not found',
	'20201': 'The Virgil Card ID header not specified or incorrect',
	'20202': 'The request sign header is invalid',
	'20203': 'Public Key value is required in request body',
	'20204': 'Public Key value in request body must be base64 encoded value',
	'20205': 'Public Key IDs in URL part and public key for the Virgil Card retrieved from X-VIRGIL-REQUEST-SIGN-VIRGIL-CARD-ID header must match',
	'20206': 'The public key id in the request body is invalid',
	'20208': 'Virgil card ids in url and authentication header must match',
	'20300': 'The Virgil application token was not specified or invalid',
	'20301': 'The Virgil statistics application error',
	'30000': 'JSON specified as a request body is invalid',
	'30100': 'Public Key ID is invalid',
	'30101': 'Public key length invalid',
	'30102': 'Public key must be base64-encoded string',
	'30202': 'Email value specified for the email identity is invalid',
	'30204': 'Application value specified for the application identity is invalid',
	'30205': 'Custom identity validation failed',
	'30303': 'Virgil Card\'s data parameters must be strings',
	'30304': 'Virgil Card\'s data parameter must be a dictionary of strings',
	'30305': 'Virgil Card custom data entry value length validation failed',
	'31000': 'Value search parameter is mandatory',
	'31010': 'Search value parameter is mandatory for the global search',
	'31030': 'Identity validation token is invalid',
	'31040': 'Virgil Card revocation parameters do not match Virgil Card\'s identity',
	'31050': 'Virgil Identity service error',
	'31051': 'Custom identity\'s validation token is incorrect',
	'31052': 'Custom identity\'s unique id was used alreaady',
	'31053': 'Custom identity\'s validation token is malformed',
	'31060': 'Identities parameter is invalid',
	'31070': 'Identity validation failed',
};
